[package]
name = "neuronode"
version = "0.1.0"
edition = "2021"
description = "NeuroStore Node"
license = "MIT"
authors = ["Janush Sahni"]

[[bin]]
name = "neuro-node"
path = "src/main.rs"

[lib]
name = "neuronode"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
rand = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
bytes = { workspace = true }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "signal", "sync", "net", "time"] }
clap = { version = "4", features = ["derive"] }
sled = "0.34"
libp2p = { version = "0.53", features = [
  "tcp",
  "dns",
  "noise",
  "yamux",
  "gossipsub",
  "kad",
  "identify",
  "ping",
  "request-response",
  "tokio",
  "macros",
  "relay",
  "autonat",
  "dcutr"
] }
serde_json = "1"
bincode = "1"
neuro-protocol = { path = "../protocol" }
chrono = { version = "0.4", features = ["clock"] }
futures = "0.3"
async-trait = "0.1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["json", "env-filter"] }
tracing-appender = "0.2"
libp2p-identity = "0.2"
base64 = "0.22"
aes-gcm = "0.10.3"
reqwest = { version = "0.12", features = ["json"] }
axum = "0.7"
tower-http = { version = "0.5", features = ["cors"] }
subtle = "2.5"
hmac = "0.12"
sysinfo = "0.30"
whoami = "1.5.1"
mac_address = "1.1.8"
keyring = { version = "3", features = ["apple-native", "windows-native", "sync-secret-service"] }
urlencoding = "2"
url = "2"
hyper = { version = "1", features = ["http1", "server"] }
hyper-util = { version = "0.1", features = ["tokio"] }
http-body-util = "0.1"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
windows-service = "0.7"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
