-- Add Two Factor Auth column
ALTER TABLE users ADD COLUMN IF NOT EXISTS two_factor_enabled BOOLEAN DEFAULT false;

-- The phone, country, and birthday columns created previously are TEXT, 
-- which perfectly hold the Base64 URL-safe strings generated by our AES-256-GCM MetadataProtector.
